services:
  db:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  rails:
    build:
      context: ./rails
    # コンテナ内での操作権限をrootに設定
    user: "root"
    command: bash -c "bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ./rails:/myapp
      - bundle_data:/myapp/vendor/bundle
      - yarn_data:/myapp/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment:
      - RAILS_ENV=development
    # この設定重要
    working_dir: /myapp
  next:
    build:
      dockerfile: ./next/Dockerfile
    command: bash -c "npm run dev"
    tty: true
    stdin_open: true
    volumes:
      - ./next:/app
    ports:
      - "8000:3000"
volumes:
  mysql_data:
  bundle_data:
  yarn_data:
