source "https://rubygems.org"
git_source(:github) {|repo| "https://github.com/#{repo}.git" }

ruby "3.3.4"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use mysql as the database for Active Record
gem "mysql2", "~> 0.5"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.1.3", ">= 7.1.3.4"

# タイムゾーン情報を提供する（標準gem）
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

gem "rack-cors"

# 環境毎の設定管理を行う
gem "config"

# ユーザー認証を提供する
gem "devise"

# devise を日本語化する
gem "devise-i18n"

# ユーザーのトークン認証を提供する
gem "devise_token_auth"

gem "active_model_serializers"

gem "rails-i18n"

gem "kaminari"

# enum を日本語化する
gem "enum_help"

group :development, :test do
  gem "bullet"
  gem "factory_bot_rails"
  gem "faker"
  gem "letter_opener_web"
  gem "pry-byebug", "~> 3.10", ">= 3.10.1"
  gem "pry-doc"
  gem "pry-rails"
  gem "rspec-rails"
  gem "rubocop-faker"
  gem "rubocop-rails"
  gem "rubocop-rspec"
end

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end
